# Generated by Django 2.0.6 on 2018-09-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180903_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='legend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='legend2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='legend3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='legend4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
