# Generated by Django 2.0.6 on 2018-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_homepost_header_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepost',
            name='title_post',
        ),
    ]
