# Generated by Django 2.0.6 on 2018-09-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180903_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='blog.PostImage'),
        ),
    ]
