# Generated by Django 2.0.6 on 2018-09-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_homepost_title_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='header_post_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_post_2', to='blog.Post'),
        ),
    ]
