# Generated by Django 2.0.6 on 2018-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_homepost_header_post_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepost',
            name='current',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
        ),
    ]
