# Generated by Django 2.0.6 on 2018-09-07 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180905_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centurie', models.IntegerField(blank=True, choices=[(1700, '18th'), (1800, '19th'), (1900, '20th'), (2000, '21th')], default=0, null=True, unique=True)),
                ('decade', models.IntegerField(blank=True, choices=[(10, '1st'), (20, '2nd'), (30, '3rd'), (40, '4th'), (50, '5th'), (60, '6th'), (70, '7th'), (80, '8th'), (90, '9th')], default=0, null=True, unique=True)),
                ('year', models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')], default=0, null=True, unique=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=0, null=True, unique=True)),
                ('date_in_mon', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('end_centurie', models.IntegerField(blank=True, choices=[(1700, '18th'), (1800, '19th'), (1900, '20th'), (2000, '21th')], default=0, null=True, unique=True)),
                ('end_decade', models.IntegerField(blank=True, choices=[(10, '1st'), (20, '2nd'), (30, '3rd'), (40, '4th'), (50, '5th'), (60, '6th'), (70, '7th'), (80, '8th'), (90, '9th')], default=0, null=True, unique=True)),
                ('end_year', models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th')], default=0, null=True, unique=True)),
                ('end_month', models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=0, null=True, unique=True)),
            ],
        ),
    ]
