# Generated by Django 2.0.6 on 2018-09-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180915_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
