# Generated by Django 2.0.6 on 2018-09-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_thumbnail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='legend2',
            new_name='content_highlight',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='legend3',
            new_name='img2_content_highlight',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='legend4',
            new_name='img2_legend',
        ),
        migrations.AddField(
            model_name='postimage',
            name='img2_use_right_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='img3_content_highlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='img3_legend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='img3_use_right_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='img4_content_highlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='img4_legend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='img4_use_right_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='use_right_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
