# Generated by Django 2.0.6 on 2018-09-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180907_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdate',
            options={'verbose_name': 'Event Date', 'verbose_name_plural': 'Event Dates'},
        ),
        migrations.AddField(
            model_name='eventdate',
            name='end_date_combo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
