# Generated by Django 2.0.6 on 2018-09-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180907_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_date', to='blog.EventDate'),
        ),
    ]
