# Generated by Django 2.0.6 on 2018-09-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180921_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='content_highlight',
            new_name='blockquote',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='img2_content_highlight',
            new_name='img2_blockquote',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='img3_content_highlight',
            new_name='img3_blockquote',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='img4_content_highlight',
            new_name='img4_blockquote',
        ),
    ]
