# Generated by Django 2.0.6 on 2018-09-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdate',
            old_name='date',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='eventdate',
            old_name='end_date',
            new_name='end_day',
        ),
    ]
