# Generated by Django 2.0.6 on 2018-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180907_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdate',
            old_name='end_date_combo',
            new_name='date',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
