# Generated by Django 2.0.6 on 2018-09-08 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_eventdate_end_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='century',
            field=models.IntegerField(choices=[(1700, '18th'), (1800, '19th'), (1900, '20th'), (2000, '21th')], default=2000),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='decade',
            field=models.IntegerField(blank=True, choices=[(10, '1st'), (20, '2nd'), (30, '3rd'), (40, '4th'), (50, '5th'), (60, '6th'), (70, '7th'), (80, '8th'), (90, '9th')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='end_century',
            field=models.IntegerField(choices=[(1700, '18th'), (1800, '19th'), (1900, '20th'), (2000, '21th')], default=2000),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='end_day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='end_decade',
            field=models.IntegerField(blank=True, choices=[(10, '1st'), (20, '2nd'), (30, '3rd'), (40, '4th'), (50, '5th'), (60, '6th'), (70, '7th'), (80, '8th'), (90, '9th')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='end_year',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_date', to='blog.EventDate'),
        ),
    ]
