# Generated by Django 2.0.6 on 2018-09-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180908_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdate',
            old_name='end_day',
            new_name='duration_day',
        ),
        migrations.RenameField(
            model_name='eventdate',
            old_name='end_decade',
            new_name='duration_decade',
        ),
        migrations.RenameField(
            model_name='eventdate',
            old_name='end_month',
            new_name='duration_month',
        ),
        migrations.RenameField(
            model_name='eventdate',
            old_name='end_year',
            new_name='duration_year',
        ),
        migrations.RemoveField(
            model_name='eventdate',
            name='end_century',
        ),
        migrations.RemoveField(
            model_name='eventdate',
            name='end_date',
        ),
    ]
