# Generated by Django 2.0.6 on 2018-09-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180908_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='century',
            field=models.IntegerField(choices=[(1700, '1700'), (1800, '1800'), (1900, '1900'), (2000, '2000')], default=2000),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='decade',
            field=models.IntegerField(blank=True, choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='duration_day',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='duration_decade',
            field=models.IntegerField(blank=True, choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90')], default=0, null=True),
        ),
    ]
