# Generated by Django 2.0.6 on 2018-09-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180908_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='decade',
            field=models.IntegerField(blank=True, choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sept'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0, null=True),
        ),
    ]
