# Generated by Django 2.0.6 on 2018-09-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180908_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
