# Generated by Django 2.0.6 on 2018-09-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20180908_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventdate',
            unique_together={('century', 'decade', 'year', 'month', 'day')},
        ),
    ]
