# Generated by Django 2.0.6 on 2018-09-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180909_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_event_date_set', to='blog.EventDate'),
        ),
    ]
