# Generated by Django 2.0.6 on 2018-09-10 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_homeposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeposts',
            name='posts',
        ),
        migrations.DeleteModel(
            name='HomePosts',
        ),
    ]
