# Generated by Django 2.0.6 on 2018-09-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_homepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepost',
            name='posts',
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Post Image', 'verbose_name_plural': 'Post Images'},
        ),
        migrations.DeleteModel(
            name='HomePost',
        ),
    ]
